[pytest]
addopts = -p pytest_homeassistant_custom_component
asyncio_mode = auto
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:litellm.*:
    ignore::DeprecationWarning:homeassistant.components.http.*:
    ignore::DeprecationWarning:homeassistant.components.climate_ip.helpers*:
    ignore::DeprecationWarning:homeassistant.components.climate_ip.connection_request*:
    ignore::pytest.PytestConfigWarning
    ignore::RuntimeWarning

markers =
    skip_legacy: marks tests as legacy for deprecated sync platforms
